;(function () {
	var Class               = require('./lib/Class'),
        AdaptationEngine    = require('./lib/AdaptationEngine'),
        Log                 = require('log');

    var JavascriptNode = Class({
        toString: 'JavascriptNode',

        construct: function () {
            this.logger = new Log(this.toString());
            this.adaptationEngine = new AdaptationEngine(this);
            this.kCore = null;
        },

        startNode: function () {
            this.logger.debug("Kevoree JavascriptNode started.");
        },

        stopNode: function () {
            this.logger.debug("Kevoree JavascriptNode stopped.");
        },

        updateNode: function () {
            this.logger.debug("Kevoree JavascriptNode updated.");
        },

        setKevoreeCore: function (kCore) {
            this.kCore = kCore;
        },

        getKevoreeCore: function () {
            return this.kCore;
        },

        /**
         * Process trace in order to do the adaptation logic on the current node
         * @param trace diff trace generated by comparing current KevoreeCore model and given model
         * @param model toDeploy model used by KevoreeCore to generate the trace
         * @returns {AdaptationPrimitive}
         */
        processTrace: function (trace, model) {
            return this.adaptationEngine.processTrace(trace, model);
        }
    });

	module.exports = JavascriptNode;
})();